[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-nids-iiot"
version = "0.1.0"
description = "Machine Learning for Network Intrusion Detection in IIoT"
readme = "README.md"
requires-python = ">=3.10"
# Dependencias extraídas de tu requirements.txt
dependencies = [
    "rich",
    "python-dotenv",
    "pandas",
    "scikit-learn",
    "torch",
    "matplotlib",
    "seaborn",
    "ipykernel",
    "ipywidgets",
    "kagglehub",
    "tqdm",
    "numpy",
    "xgboost",
    "lightgbm",
    "catboost",
    "shap",
    "lazypredict",
    "imbalanced-learn"
]

[tool.setuptools]
packages = ["src"]